### ISSUE TITLE
Column variants

### ISSUE THREAD

**Issue by heyjudek** [Brandcraf06/Blockus#104]
Would you consider adding column variants of the added blocks?
This mod has done it very simply - https://www.curseforge.com/minecraft/mc-mods/columns
Or this one - https://www.curseforge.com/minecraft/mc-mods/corail-pillar

I have tested the first one and even made custom blocks, it works as intended.

**Comment by Brandcraf06** [comment]
I hadn't really thought about it

**Comment by heyjudek** [comment]
Would you be willing to add these though? As a non-modder, I have managed to register a few blocks and then used the blockstate+model file of the columns from the first mod to create costum columns which work exactly like the original ones. So, it would be pretty quick to add them and there won't be any need for additional textures since they all use the textures of the parent block.

**Comment by Brandcraf06** [comment]
Yes, why not it can be cool, I can look at the files of the first mod for the columns? I could add columns for some blocks, like those with walls variant and/or pillars
