### ISSUE TITLE
[2.1.1+21w16a] Blocks Lack Effective Tools

### ISSUE THREAD

**Issue by lcena** [Brandcraf06/Blockus#108]
The majority of blocks lack an effective tool, also making them unharvestible once placed. I’ve seen this in:

> -every cut/chiseled/smooth stone variety (vanilla varieties are unaffected), stairs, and slabs.
-gold/iron gates
-and legacy blocks.

From what I can tell, blocks that require an axe work as intended. Glass/glass adjacent blocks, blocks that use a shovel, and blocks that don’t need a tool at all like crates and sugar blocks function fine.

As far as I can see, the issue is just with blocks that require a pickaxe to harvest,

There are some exceptions though, stone walls function as intended for some reason, and a few compact blocks work (Ender block, block of nether star) while the charcoal block doesn’t.

My apologies if the snapshot releases aren’t really maintained regularly, I haven’t seen anyone else bring up the issue for this release though so I figured I should give some input.

**Comment by Brandcraf06** [comment]
Fixed
