### ISSUE TITLE
[Request] Support for more 1.17 blocks

### ISSUE THREAD

**Issue by oliviathevampire** [Brandcraf06/Blockus#114]
I would love support for calcite, tuff, amethyst, copper and other 1.17 blocks.

**Comment by Brandcraf06** [comment]
This is obviously planned, except for calcite (Too close to the existing marble)

What I miss for now is the textures.

**Comment by oliviathevampire** [comment]
I can help with textures possibly

**Comment by SpiderKolo** [comment]
Trying to think of a idea for Calcite blocks...
What if... there could be Calcite specific blocks which for them to exist would need to be paired with another resource?

Maybe Amethyst could be fitting?

**Comment by Brandcraf06** [comment]
I put this as completed, even though all 1.17 blocks don't especially have variants in the mod yet. And also because 1.17 is now a little dated.
