### ISSUE TITLE
white oak

### ISSUE THREAD

**Issue by gamerqueen1** [Brandcraf06/Blockus#115]
hi so the white oak in you mod only drops leaves it doesn't drop any saplings

**Comment by Brandcraf06** [comment]
What version of the mod are you playing with? Normally this problem is solved in the latest version (2.2.1+1.17).

**Comment by gamerqueen1** [comment]
I was playing on 1.17

**Comment by Brandcraf06** [comment]
If you play with 2.2.0+1.17 version of the mod, update to 2.2.1+1.17

**Comment by gamerqueen1** [comment]
Thanks, I'll check it out.
