### ISSUE TITLE
[bug] blackstone doors have no effective tool

### ISSUE THREAD

**Issue by milkev** [Brandcraf06/Blockus#117]
blackstone doors have no effective tool, and are not dropped no matter what they are mined with.

should probably be a pickaxe, seeing as they are made of stone

**Comment by milkev** [comment]
all stone-like-material buttons and pressure plates have the same issue. the wooden ones do not
tested with the updated version where doors are mineable correctly

**Comment by Brandcraf06** [comment]
> all stone-like-material buttons and pressure plates have the same issue. the wooden ones do not
> tested with the updated version where doors are mineable correctly

Mojang and its effective tool management for stone buttons and pressure plates... I didn't see that they did it that way, so it makes sense. Fixed in next version, with the addition of the blackstone button effective tool that Mojang themselves have forgotten.
