### ISSUE TITLE
Flowering azalea small hedges are not flowers

### ISSUE THREAD

**Issue by haykam821** [Brandcraf06/Blockus#123]
Unlike flowering azaleas and flowering azalea leaves, flowering azalea small hedges are not in the `minecraft:flowers` block and item tags. As a result, they do not allow bee nests to grow from saplings, cannot be pollinated by bees, and cannot be used to breed bees.

**Comment by Brandcraf06** [comment]
Flowering azalea small hedge is already in `minecraft:flowers` tags
