### ISSUE TITLE
Ice bricks do not have slab or stair variants

### ISSUE THREAD

**Issue by haykam821** [Brandcraf06/Blockus#130]
Unlike snow bricks, ice bricks only have a wall variant.

!['Ice Brick' search](https://user-images.githubusercontent.com/24855774/124781521-7678d300-df11-11eb-9856-66e908e5bf58.png)

**Comment by Brandcraf06** [comment]
It's intentional, I encountered a problem with slipperiness and blocks that don't have at least a full hibox.
