### ISSUE TITLE
Only marble has a chiseled pillar variant

### ISSUE THREAD

**Issue by haykam821** [Brandcraf06/Blockus#131]
The following list of blocks have a pillar variant but no chiseled pillar variant:

* Purpur (vanilla pillar)
* Quartz (vanilla pillar)
* Stone brick
* Polished andesite
* Polished diorite
* Polished granite
* Tuff
* Deepslate
* Polished blackstone
* Polished basalt
* Limestone
* Marble
* Bluestone
* Snow
* Ice
* Blaze
* Nether
* Red nether
* Charred
* Teal
* Obsidian
* Dark prismarine
* Prismarine
* Sandstone
* Red sandstone
* Soul sandstone
* End stone
* Phantom purpur

**Comment by Brandcraf06** [comment]
Intentional, at least for now, for the marble style. But maybe in the future there will be more. For now I'm concentrating on other stuff
