### ISSUE TITLE
Tuff brick and mossy deepslate brick walls are in the 'Building Blocks (Blockus)' item group

### ISSUE THREAD

**Issue by haykam821** [Brandcraf06/Blockus#134]
Instead of being in the 'Decoration Blocks (Blockus)' item group, similar to how vanilla walls are in the 'Decoration Blocks' item group, tuff brick and mossy deepslate brick walls are in the 'Building Blocks (Blockus)' item group:

![Tuff brick and mossy deepslate brick walls in the 'Building Blocks (Blockus)' item group](https://user-images.githubusercontent.com/24855774/124791207-da06fe80-df19-11eb-8339-3b5ae0635f1c.png)

https://github.com/Brandcraf06/Blockus/blob/9ac5b299d72c598e0b5aa477cd7bed494fab4034/src/main/java/com/brand/blockus/content/BlockusItems.java#L67

https://github.com/Brandcraf06/Blockus/blob/9ac5b299d72c598e0b5aa477cd7bed494fab4034/src/main/java/com/brand/blockus/content/BlockusItems.java#L78

**Comment by Brandcraf06** [comment]
Fixed here: https://github.com/Brandcraf06/Blockus/commit/3d5ebb3d09740d757a0f229e9691b1ebc7cb6ad6
