### ISSUE TITLE
Option to turn off swamp colors for water bricks?

### ISSUE THREAD

**Issue by elamea** [Brandcraf06/Blockus#173]
I play with Optifine which allows me to turn off swamp colors (personal preference) however I was building with the water bricks in the swamp biome and noticed they did not match the water. It would be great if there was a config file that allowed for turning off swamp colors on certain Blockus blocks! (I don't know if the swamp affects any other blocks?)

![2021-08-05_20 05 08](https://user-images.githubusercontent.com/87742576/128440501-4078d48a-4fee-4a00-b8b5-13b6b0cb33d2.png)

**Comment by haykam821** [comment]
This is a bug with Optifine, since the color of water bricks always matches the color of water.

**Comment by Brandcraf06** [comment]
Water bricks no longer change with biome colors
