### ISSUE TITLE
[Bug] Soul Fire can be lit on Slabs and Stairs... when they shouldn't have.

### ISSUE THREAD

**Issue by SpiderKolo** [Brandcraf06/Blockus#191]
I think the best way to describe the bug is by showing it...

![2021-09-24_05 10 43](https://user-images.githubusercontent.com/62638498/134612466-dd64941d-621c-4a2b-b390-5a89266d041d.png)
![2021-09-24_05 10 52](https://user-images.githubusercontent.com/62638498/134612470-f98c29ee-fb99-4862-9d91-4786049543e7.png)

Not big issue, just a bit surprised that this is possible.

**Comment by Brandcraf06** [comment]
I know, this is a vanilla bug when you put a non-full block in soul fire tag (that's ridiculous but I can't do anything)
https://bugs.mojang.com/browse/MC-214503

**Comment by SpiderKolo** [comment]
Got an idea how maybe it could be fixed, but I don't know how to write such a fix as I don't know how to code:

Maybe you could exclude non-full blocks out of the tag... and then if a game would try to set this block on fire and it's those slabs or stairs in specific orientation (slabs being on top-half of block, stairs being basically upside-down), then mod would attempt to replace the normal fire with soulfire one.

You could add a new tag which would be specifically for soul variants of slabs and stairs, so the mod would check for blocks in that tag.

Of course we hope that Mojang will fix this vanilla bug some day, but in the meanwhile that's the best I can think of...

**Comment by muzikbike** [comment]
Yes isn't this basically https://github.com/VazkiiMods/Quark/issues/2711?
