### ISSUE TITLE
Barrels not compatible for 3rd party mod recipes

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Brandcraf06/Blockus#194]
Blockus barrels for 1.18 are not compatible with mod recipes that require a Minecraft barrel `minecraft:barrel`.
For example, Dank Storage (I'm using the 1.17 version in the snapshot 21w44a) requires a vanilla oak barrel.
If the barrels cannot be made compatible, then an option to disable them would be nice

**Comment by Brandcraf06** [comment]
Barrels recipes removed for some reasons
