### ISSUE TITLE
Crafting table...uncraftable?? and a few more

### ISSUE THREAD

**Issue by susan3333333** [Brandcraf06/Blockus#196]
On the fabric 1.8 snapshot version, I am unable to craft quite a few, apparently random, vanilla items.
Starting with the crafting table.......

Mods I have:
  AdditionalAdditions-3.0.0
  BlockOf-Beta-1.2
  blockus-2.3.1+1.18-pre5
  canvas-fabric-mc118-1.0.2223
  DynamicSoundFilters-1.3.0+1.18
  extshape-1.3.1-mc1.17+
  fabric-api-0.42.8+1.18
  fabric-language-kotlin-1.6.5+kotlin.1.5.31
  FallingTree-1.18-pre2-2.14.3
  Gobber2-Fabric-1.18-pre5-2.5.45
  InventoryProfilesNext-fabric-1.18-1.1.6
  justcoppertools-1.18-pre5-0.1.1
  kibe-1.9.4-BETA+1.18
  Mambience-3.2.0+1.18
  MiningDimensions_Fabric-1.18-pre5-1.2.27
  Mo-Glass-1.5-MC1.18-pre5
  MobCatcher-Fabric-1.18-pre5-1.1.13
  modmenu-3.0.0
  WardBlocks-Fabric-1.18-pre5-1.2.16
  windchimes-1.2.0

**Comment by Brandcraf06** [comment]
What ? It certainly has nothing to do with Blockus specifically

**Comment by susan3333333** [comment]
I don't know the cause, but removing blockus is the only way to fix it :(
