### ISSUE TITLE
Upgrading to from 1.17.1 to 1.18 wipes out barrel contents

### ISSUE THREAD

**Issue by barribob** [Brandcraf06/Blockus#197]
I had a while oak log barrel with some contents in it in 1.17.1 version of the mod. I copied the save folder to a separate instance using the 1.18-rc3 version, but when I opened the barrel it was empty. Saving and loading in 1.18 seems to still work, just upgrading versions wipes out the block entity or something like that.

**Comment by Brandcraf06** [comment]
That's strange... I'll see if I can find the problem.
Anyway I don't recommend to transfer a modded save from one minecraft version to another. Concerning Blockus, some Block IDs have changed which may cause some blocks to disappear from your world

Note: Blockus barrels are no longer craftable in 1.18 - it's intentional

**Comment by haykam821** [comment]
This is an issue with all modded block entities: FabricMC/fabric#1837

**Comment by Brandcraf06** [comment]
> This is an issue with all modded block entities: [FabricMC/fabric#1837](https://github.com/FabricMC/fabric/issues/1837)

Thanks for the info

**Comment by AmbitiousAlan** [comment]
I also had disappearing content from barrels, but that a minor issue. I can just swap the content from my few barrels into chests.

"some Block IDs have changed which may cause some blocks to disappear from your world" This explains my stone pillars disappearing. Is there a fix for this?

"Anyway I don't recommend to transfer a modded save from one minecraft version to another." How do you suggest you bring a modded world to another version? Or do you hold the opinion when you play a modded game, you should accept to remain in that version forever and to just start another world if you want to play the more recent versions?

Many mods that I used in 1.17 are not updated yet and that's fine. They don't break anything by being absent. But block mods break your world if you don't keep them compatible. 

Why did you change the block IDs in the first place?
Is there an easy way to fix this before bringing the save into 1.18?

**Comment by AmbitiousAlan** [comment]
I see. You changed stone_bricks_pillar to stone_brick_pillar.
That's a dumb reason to break worlds but ok. 

Can't you have put something that looked at the old blocks and converted them to the new IDs?

**Comment by haykam821** [comment]
> Can't you have put something that looked at the old blocks and converted them to the new IDs?

Data fixers are difficult to implement for mods. If an API becomes available for data fixing, it will be used the next time IDs are changed.

> Why did you change the block IDs in the first place?

Some IDs are inconsistent or plain wrong. For example, `andesite_bricks_stairs` is inconsistent with vanilla IDs like `stone_brick_stairs`.

> Or do you hold the opinion when you play a modded game, you should accept to remain in that version forever and to just start another world if you want to play the more recent versions?

It's possible to upgrade, but you shouldn't always expect every mod to be data-compatible between versions. The primary focus is to remain data-compatible within Minecraft versions, but you will have to exercise caution when upgrading any mods. That holds true for almost every mod, and it's why you should make backups.

**Comment by AmbitiousAlan** [comment]
> It's possible to upgrade, but you shouldn't always expect every mod to be data-compatible between versions. The primary focus is to remain data-compatible within Minecraft versions, but you will have to exercise caution when upgrading any mods. That holds true for almost every mod, and it's why you should make backups.

Yes. I have a backup. I don't care for all other mods except mods that add blocks and computercraft.

> Data fixers are difficult to implement for mods. If an API becomes available for data fixing, it will be used the next time IDs are changed.

Bummer. How can I change it manually? How can I find a list of all block IDs for a given mod?
