### ISSUE TITLE
Client Crash: Rendering item

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Brandcraf06/Blockus#198]
I was moving things around in inventory and the client crashed.

Minecraft: 1.18
Blockus 2.3.3+1.18
Modpack: [99 Mods on the Wall: Fabric Edition](https://www.curseforge.com/minecraft/modpacks/ninety-nice-99-mods-on-the-wall-fabric-edition)

[crash-2021-12-02_15.45.32-client.txt](https://github.com/Brandcraf06/Blockus/files/7645577/crash-2021-12-02_15.45.32-client.txt)

**Comment by ClaudiusMinimus** [comment]
I am getting more reports of this exact crash

**Comment by Brandcraf06** [comment]
It's strange, I have no problem with the mod alone... 
It seems to come from flex/canvas. Or incompatibility between Blockus and this.
I can't test with your modpack for the moment because I can't launch it (crash at startup, I don't know if it's me, the 1.18 or the pack)

**Comment by ClaudiusMinimus** [comment]
It could be the pack, but I have had over 1,200 downloads in less than a week. If someone has had issue, then reinstalling the pack fixed it everytime. Can you try re-installing it? What launcher are you using? I'll be uploading a new version this afternoon. I will let you know when it is available.

**Comment by ClaudiusMinimus** [comment]
I actually removed canvas in v1.5.0 (soon to be released), so it may be fixed by virtue of removing it.

**Comment by Brandcraf06** [comment]
I don't have any problems with the last version of your modpack

**Comment by ClaudiusMinimus** [comment]
This last version of the pack is running smoother. Thank you for taking a
look at it! If it happens again I will notify you.
Thanks,
CM
PS: Thanks for a great mod!
