### ISSUE TITLE
Log warning (probably nothing)

### ISSUE THREAD

**Issue by Shockks** [Brandcraf06/Blockus#199]
Was troubleshooting another mod and saw this in the log file, unsure if you wanted to know as it is just a warning but thought i would mention it.

- libcd 3.0.3+1.16.3 via blockus

[ForkJoinPool-1-worker-6/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12

**Comment by Brandcraf06** [comment]
Yes I know, but I can't do anything, it comes from [Libcd](https://www.curseforge.com/minecraft/mc-mods/libcd)
