### ISSUE TITLE
Barrel block deletes items

### ISSUE THREAD

**Issue by stuin** [Brandcraf06/Blockus#2]
I placed down an oak barrel, put some items in it, and next time I opened it they were gone. Relogging and placing new items yielded no fix, barrel is always empty when I open it. Breaking it only returns the barrel.

**Comment by JamiesWhiteShirt** [comment]
Can confirm this is an issue. Had to stick to vanilla barrels.

**Comment by JamiesWhiteShirt** [comment]
In some update BarrelBlockEntity started checking for `Blocks.BARREL` in its tick method. Whenever someone is looking into the barrel, the block entity is invalidated.

**Comment by Brandcraf06** [comment]
Fixed in 1.1.6.1
