### ISSUE TITLE
Port to 1.18.2

### ISSUE THREAD

**Issue by kittech0** [Brandcraf06/Blockus#219]
Port for fabric 1.18.2

**Comment by K0-RR** [comment]
Wow, what a nice way of asking. The dev is already working on it so chill.
https://github.com/Brandcraf06/Blockus/tree/1.18.2

**Comment by Brandcraf06** [comment]
I'm just waiting for an API to be updated so I can update Blockus to 1.18.2

Be patient

**Comment by kittech0** [comment]
I just asked for TODO rather than now

**Comment by kittech0** [comment]
i didnt meant to be it now
