### ISSUE TITLE
Shingles cannot be made from uncolored terracotta

### ISSUE THREAD

**Issue by annrandall** [Brandcraf06/Blockus#222]
With Blockus 1.18.1, shingles can no longer be made on the crafting table from plain terracotta. Colored terracotta seems to still work. We are using REI for our recipes.

**Comment by Brandcraf06** [comment]
Oops, this will be fixed soon

**Comment by Brandcraf06** [comment]
Fixed
https://www.curseforge.com/minecraft/mc-mods/blockus/files/3693338
