### ISSUE TITLE
Wall Signs Texture error

### ISSUE THREAD

**Issue by CongYuSanXun** [Brandcraf06/Blockus#229]
Bamboo Sign Texture error
![huge_2022-03-24_13 59 48](https://user-images.githubusercontent.com/68322529/159852288-bf639acc-747f-4e2e-b383-240425bf69c8.png)

**Comment by Brandcraf06** [comment]
It's weird, maybe a problem with the API I use. 
Thanks for report this

**Comment by CongYuSanXun** [comment]
> 很奇怪，可能是我使用的 API 有问题。 感谢您报告这个

Thanks for your contribution。
