### ISSUE TITLE
[MC 1.15.2 - Blockus 1.3.1] Exp Orbs touch Asphalt Causes Crash

### ISSUE THREAD

**Issue by Dragonsissiy** [Brandcraf06/Blockus#23]
Hello!

Thank you so much for keeping this mod updated and adding awesome blocks! This is by far one of my favorites. I just wanted to let you know of a funny crash we get on my server. 
[Server Crash Log](https://github.com/Brandcraf06/Blockus/files/4163174/crash-2020-02-05_20.05.29-server.txt)
![CurrentModsList](https://user-images.githubusercontent.com/60621847/73905525-6b210400-4854-11ea-8859-fae8b341a6da.PNG)

Thanks again,
-Dragon_sissiy

**Comment by Dragonsissiy** [comment]
Upon more testing, it seems it's not necessarily the act of breeding, but when EXP orbs touch the asphalt. We tested it with killing mobs, dropping xp potions, etc. all result in cashing when the exp touches the asphalt blocks.

**Comment by Dragonsissiy** [comment]
Just tested this with falling sand, which reproduces the same issue. However, arrows touching/falling on it does not reproduce this issue.

**Comment by Brandcraf06** [comment]
> Just tested this with falling sand, which reproduces the same issue. However, arrows touching/falling on it does not reproduce this issue.

Thanks for reporting that! After testing, the game try to give speed effect to non-living entities. It will be fixed very soon !

**Comment by Dragonsissiy** [comment]
> 
> Thanks for reporting that! After testing, the game try to give speed effect to non-living entities. It will be fixed very soon !

You're welcome and thank you! Glad I could help. :D
