### ISSUE TITLE
Overpowered Golden Apple/Carrot Crate recipes

### ISSUE THREAD

**Issue by Seeker14491** [Brandcraf06/Blockus#235]
These two recipes for Golden Apple Crates and Golden Carrot Crates let you make Golden Apples and Golden Carrots using about 8x less gold/apples/carrots as compared to the vanilla recipes.

![Screenshot 2022-04-23 182808](https://user-images.githubusercontent.com/6490497/164949393-1a922166-3174-4882-9414-371869fe1a61.png)
![Screenshot 2022-04-23 182828](https://user-images.githubusercontent.com/6490497/164949394-66f2ab8b-e359-4aa5-ad59-97bccbf14e4b.png)

**Comment by Brandcraf06** [comment]
Oops, the result should not be 8 crates. Thanks for report ! This will be fixes very soon
