### ISSUE TITLE
White Oak Barrel doesn't have a recipe but others do

### ISSUE THREAD

**Issue by TheVastidious** [Brandcraf06/Blockus#238]
We have version 2.4.5 running in 1.18.2 (with the Better Minecraft 1.18.2 (Fabric) modpack and we want to make a bunch of White Oak Barrels. The only option we have is to use creative or a mod command to /give a bunch to players. We could see that many barrels that have recipes but it seems just the white oak was missing one. Is that something that can be added?

**Comment by haykam821** [comment]
These recipes were removed from Blockus because the barrels were deprecated. What are the recipe identifiers for these barrel recipes? The modpack itself is likely adding them back.

**Comment by TheVastidious** [comment]
I'm sorry I just double checked and the ones with Blockus don't have recipes. I thought I saw that they did. Many of the recipes I saw are added with other mods, like Better End, Better Nether, and Edenring.

**Comment by ardissaps** [comment]
can confirm, all the barrel don't have recipe,

**Comment by Brandcraf06** [comment]
This is intentional for the missing recipes, if there is the barrels recipes it's that a mod adds them again

I don't know yet if they will come back
