### ISSUE TITLE
[MC 1.15.2 - Blockus 1.3.2] Possible Blocks Conflict

### ISSUE THREAD

**Issue by Dragonsissiy** [Brandcraf06/Blockus#24]
Hey Brandcraf06!

Thank you so much for fixing the bug we encountered! <3 I appreciate all your hard work! I just wanted to let you know of, from my understanding, a possible block conflict with the mod Simple BC Pipes. That mod owner also, generously and recently updated that mod but upon installing it I noticed that it makes many of the blocks from your mod disappear. Both in the MC creative mode menu and REI. I believe it's specific to the asphalt blocks. (but not slabs.) I already added this info to the other mod and wanted to include it here just in case there would end up needing some collaborative effort. Please let me know if there is anything else I can help with.

Screenshots:
![CurrentModsList](https://user-images.githubusercontent.com/60621847/74002866-60826f80-4925-11ea-9b51-8104923b1cf6.PNG)

![LookingAtBlockus_Random](https://user-images.githubusercontent.com/60621847/74002887-74c66c80-4925-11ea-92d6-1c436eab6ac2.png)

![LookingAtBlockus_OrangeAsphalt](https://user-images.githubusercontent.com/60621847/74002896-7abc4d80-4925-11ea-877d-6f5bf9261b10.png)

![LookingAtMenu_MissingBlocks](https://user-images.githubusercontent.com/60621847/74002905-83ad1f00-4925-11ea-96f3-6453fe0986fb.png)

![LookingAtMenu_MissingBlockusBlocks](https://user-images.githubusercontent.com/60621847/74002912-8740a600-4925-11ea-93dc-e4c442ca47aa.png)

Here is the link to the other thread for reference:
https://github.com/AlexIIL/SimplePipes/issues/36

-Dragon_sisiy

**Comment by AlexIIL** [comment]
After some debugging it turns out this is an issue with how SimplePipes scans blocks for facades - essentially it scans the block just after it is registered (but before the item is registered)  and calls `Block.asItem()`, which then looks up the item to find... nothing. It then caches nothing for next time (woops) and then the correct item is registered.

So it's a SimplePipes bug.

**Comment by AlexIIL** [comment]
Ok, this should now be fixed in simple pipes 0.3.5 - can you close this issue please?
