### ISSUE TITLE
Timber fames make less than is sensible

### ISSUE THREAD

**Issue by NoahSlocombe** [Brandcraf06/Blockus#244]
It takes 4 timber frames to produce only one of the diagonal timber frames, and 4 of those to produce only one of the cross timber frames. This means that you need 16 timber frames to produce only one of the cross timber frames. Is this intended behaviour?

Similarly, it takes 2 wooden planks and 2 paper to product only 1 timber frame, meaning 32 planks are required for 1 cross timber frame.

**Comment by Brandcraf06** [comment]
Oops this is a mistake. no this is not intended. 

Normally 2 planks + 2 paper gives 2 timber frame
And 4 Timber frame gives 4 Diagonal Timber Frame & 4 Diagonal Timber Frame gives 4 Cross Timber Frame

But I forgot the output count in the recipes... it will be quickly fixed, thanks for reporting
