### ISSUE TITLE
Give Non Striped Bamboo some love (Green)

### ISSUE THREAD

**Issue by ardissaps** [Brandcraf06/Blockus#247]
Bamboo blocks that are still green not striped

**Comment by Brandcraf06** [comment]
Maybe this will be added in Blockus 1.20, since bamboo boards will be a vanilla thing.

**Comment by Brandcraf06** [comment]
Maybe this will be added in Blockus 1.20, since bamboo planks will be a vanilla thing.

**Comment by Brandcraf06** [comment]
Added in 1.20 (replace <1.19 Bamboo Planks)
