### ISSUE TITLE
Barrel Recipe isnt working or showing up in REI

### ISSUE THREAD

**Issue by Akane-N** [Brandcraf06/Blockus#251]
Hello for some reason I'm unable to craft blockus barrels all of a sudden. they were working fine on my server at the start, I was able to craft charred barrels, but recently (I haven't changed anything on my end) I went to craft more and its only giving me vanilla barrels now...what happened? I'm so confused why its not working suddenly.

**Comment by DrUltraLux** [comment]
Yep, not only does it make all barrel uncraftable, but it breaks any other mod that adds more barrels as well.
