### ISSUE TITLE
Blockus Blocks Disappearing When Updating Server from 1.18.2 to 1.19.2

### ISSUE THREAD

**Issue by ChopTV** [Brandcraf06/Blockus#263]
I'm in the process of trying to update our Fabric server to 1.19, and I'm running into an issue where all of the Herringbone Brick blocks are just disappearing once the world loads in 1.19.2. The two blocks that I've confirmed so far are Herringbone Andesite Brick and Herringbone Diorite Brick. Weirdly, when I place the blocks in the world in 1.19, Hudium tells me that they aren't mineable. So I'm not sure if this is part of the problem or not. 

This particular world was updated from 1.17 to 1.18 and the blocks survived.

**Comment by Brandcraf06** [comment]
Sorry, this is because some blocks ID have changed (Without datafixers) between 1.18 and 1.19, especially the herringbone blocks
