### ISSUE TITLE
Limestone looks wrong

### ISSUE THREAD

**Issue by Happyfrozenfire** [Brandcraf06/Blockus#268]
I was wandering through the world when I saw a patch of limestone generate among stone. It looked out of place. I think the color contrast makes it feel more like a legacy texture. 
Additionally, limestone IRL is traditionally much less sandy-looking and much less yellow. Maybe consider renaming it?

**Comment by Brandcraf06** [comment]
What do you think about it 
![image](https://user-images.githubusercontent.com/16505254/204086261-c27e138b-d252-475f-b815-c1a8d0d7d336.png)
