### ISSUE TITLE
Crash with version 1.4.0

### ISSUE THREAD

**Issue by Dragonracer1973** [Brandcraf06/Blockus#27]
[crash-2020-03-17_19.09.56-client.txt](https://github.com/Brandcraf06/Blockus/files/4346396/crash-2020-03-17_19.09.56-client.txt)

**Comment by Linguardium** [comment]
Seems like 1.4.0 for 1.15.2 was compiled with 1.16 mappings

**Comment by Brandcraf06** [comment]
The mod doesn't like the latest loader version , it's now fixed in 1.4.1 thank you for the report!

**Comment by Dragonracer1973** [comment]
glad to help, love the mod, have you thought of implementing cobble versions of andesite, doirite, and granite?
