### ISSUE TITLE
Blocks Not Placing

### ISSUE THREAD

**Issue by LuiRG** [Brandcraf06/Blockus#272]
Whenever I try to place a block from the mod it just places and dissapears a second after, here's a list of my modpack if it may help
![image](https://user-images.githubusercontent.com/65868403/214085665-6bae370b-8c1d-4f65-bbe5-202dc632f8fa.png)

**Comment by Brandcraf06** [comment]
It doesn't seem to come from Blockus, maybe a block placement protection.
