### ISSUE TITLE
Button recipes confused with trapdoor/wall

### ISSUE THREAD

**Issue by SolidBlock-cn** [Brandcraf06/Blockus#281]
For example, the recipe of *Marble Wall* is the same as *Marble Button*, which consists of 6 *Marble Block*s. I think the recipe of button is incorrect.
Refer to `offerPressurePlateButtonRecipe` method in `BlockusRecipeProvider`, which invoked `createTrapdoorRecipe` for button recipe.

**Comment by Brandcraf06** [comment]
Oops what a mistake ! I'll fix it right away
There was the same thing with the pressure plates

Thanks for reporting me this
