### ISSUE TITLE
Blockus and Proxy Conflict

### ISSUE THREAD

**Issue by Moosheking** [Brandcraf06/Blockus#301]
Blockus messes up block data if you join a server that runs off a proxy

![2023-07-31_22 46 38](https://github.com/Brandcraf06/Blockus/assets/124766234/64cc40d8-21b2-4cd6-aeba-2e042ed299b8)

Recreation:
Download Fabric 1.20.1
Download Blockus 2.7.4
Connect to our server.
mc.oresfallorigins.com

See the bugged out mess

**Comment by kittech0** [comment]
the issue has been found in multiple mods. (im network engineer of the server)

**Comment by kittech0** [comment]
Basically the mod breaks blocks on vanilla servers.
This bug can be found in multiple mods like: traverse, dawn api, cinderscapes, blockus, terrestria
