### ISSUE TITLE
Nether star block grants infinite health

### ISSUE THREAD

**Issue by Sinogard** [Brandcraf06/Blockus#302]
I'm not sure why but absorption doesnt seem to have a cooldown, applies instantly, and stacks infinitely. 
![Screenshot 2023-08-04 063830](https://github.com/Brandcraf06/Blockus/assets/88293626/5bbd6902-5a3b-4633-9d48-5dd538922d93)
Screenshot shows things off the block and doesnt seem to go away despite logging out

**Comment by Brandcraf06** [comment]
Wow, I tested in 1.19.2, 1.19.4 & 1.20.1 and I couldn't reproduce this.
What version of minecraft/mod are you using?

**Comment by Sinogard** [comment]
1.20.1
Heres the instance I'm using. Click and drag it into MultiMC and it will recreate it with my configs. 
Its not giving me any errors server side.
https://drive.google.com/file/d/16NJS50Nf5denIUtaG3HPLWb7np7SmZEe/view?usp=sharing

**Comment by Brandcraf06** [comment]
Indeed, I think there's a compatibility issue with a mod that accumulates absorption effects. It also does it when you eat a golden apple.
However, I've searched and can't help you figure out which one, sorry..

**Comment by Sinogard** [comment]
it would be easy if there was a log of some kind but oh well. Thanks.

**Comment by Brandcraf06** [comment]
I persevered and found it! 
The mod is **Big Extra**.

**Comment by Sinogard** [comment]
oh thank god. I was running through configs and not finding it. Is there a fix I can implement?

**Comment by Brandcraf06** [comment]
I don't know, I haven't even seen a config option mentioning this behavior. I recommend you to report the bug on the mod page :
https://github.com/shiftthedev/BigExtras/issues

**Comment by Sinogard** [comment]
sounds good. Thank you so much.
