### ISSUE TITLE
Can't burn in furnace wooden mosaic stairs and slabs into charred ones (title edited)

### ISSUE THREAD

**Issue by SolidBlock-cn** [Brandcraf06/Blockus#310]
Herringbone planks (as well as their variants) can be burned in furnace into charred herringbone planks. However, wooden mosaics do not have such conversion.

**Comment by Brandcraf06** [comment]
Wooden Mosaics (except crimson/warped & charred) can already be burned in a furnace into Charred Mosaic

**Comment by SolidBlock-cn** [comment]
I made a mistake. I mean, wooden mosaic stairs and slabs cannot be charred.

**Comment by Brandcraf06** [comment]
Oh I see, yes only full wooden planks can be turned into charred, not stairs/slabs etc... and that's intentional. This is the case for classic planks. Herringbone Stairs/Slabs don't exist.
