### ISSUE TITLE
Iron platings and gold platings are not beacon base blocks

### ISSUE THREAD

**Issue by SolidBlock-cn** [Brandcraf06/Blockus#311]
I found iron bricks and gold bricks (as well as stairs and slab) are beacon base blocks. However, iron platings and gold platings are not. Is that worked as intended?

**Comment by Brandcraf06** [comment]
Yes, that work as intended, because Iron/gold plating is based on ingots and with the recipe, it would make the beacon pyramid much more easy to do. Whereas [Ore] Bricks are based on a [Ore] Block.
