### ISSUE TITLE
Flower Pot bug

### ISSUE THREAD

**Issue by Ratmonster04** [Brandcraf06/Blockus#324]
Whenever I place a plant into a vanilla flower pot it turns into a large flower pot for some reason. I think this might be bug.

**Comment by haleyjd** [comment]
Same here, with [Blockus 2.8.4+1.20.4](https://modrinth.com/mod/blockus/version/2.8.4+1.20.4). Pre-existing pots placed in the world are OK but new ones being filled transform into the large pots, and stay as large pots when emptied or broken.
