### ISSUE TITLE
Modded signs drop modded hanging signs / Hanging signs didn't drop anything

### ISSUE THREAD

**Issue by AphoticGoblin** [Brandcraf06/Blockus#325]
https://medal.tv/games/minecraft/clips/2bHOJsMWMcmsxx/d1337nwD5XsN?invite=cr-MSxjNjYsMjA4Mjg4MzI2LA

Latest version of fabric 1.20.1

**Comment by Brandcraf06** [comment]
Fixed in next update, I hadn't noticed this.... now signs drop signs and hanging signs drop hanging signs.

And the hanging signs didn't drop anything before this fix too.
