### ISSUE TITLE
Mismatched blocks

### ISSUE THREAD

**Issue by Wytchcat** [Brandcraf06/Blockus#331]
Using Fabric Server, fabric API 0.100.3 and Blockus... I get lots of mismatched blocks. Water instead of snow, mosaic tile (or maybe carpet) for bamboo, sand for jungle vines etc.

No error in console.

**Comment by Brandcraf06** [comment]
I really don't see why Blockus would be the cause, but it's a very weird bug and I don't know why.

**Comment by Wytchcat** [comment]
No worries.. we've found new bugs to take our attention. LOL
