### ISSUE TITLE
Game won't start... looking for 1.21.1 or above despite being marked 1.21

### ISSUE THREAD

**Issue by Wytchcat** [Brandcraf06/Blockus#335]
Running 1.21 with Fabric 0.16.3 loader...

Download from Modrinth or Curseforge says 2.9.3 is compatible and pushing update but crashes with following error on sever.

10:34:03  [Info] Loading Minecraft 1.21 with Fabric Loader 0.16.3
10:34:03  [Warn] Mod netherdepthsupgrade uses the version fabric-3.1.8-1.21 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
10:34:03  [Warn] Mod resolution failed
10:34:03  [Info] Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED blockus 2.9.3+1.21.1 {depends minecraft @ [~1.21.1]}, ROOT_FORCELOAD_SINGLE blockus 2.9.3+1.21.1]
10:34:03  [Info] Reason: [HARD_DEP blockus 2.9.3+1.21.1 {depends minecraft @ [~1.21.1]}]
10:34:03  [Info] SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, fabric-keybindings-v0, modmenu, fabric-client-tags-api-v1, nemos-ambience, fabric-screen-api-v1, nether-coords, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, fabric-rendering-v0, fabric-sound-api-v1, fabric-key-binding-api-v1, fabric-rendering-v1]
10:34:03  [Info] Fix: add [], remove [], replace [[blockus 2.9.3+1.21.1] -> add:blockus 1 ([(-∞,∞)])]
10:34:03  [Error] Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
- Replace mod 'Blockus' (blockus) 2.9.3+1.21.1 with any version that is compatible with:
- minecraft 1.21
More details:
- Mod 'Blockus' (blockus) 2.9.3+1.21.1 requires any version between 1.21.1 (inclusive) and 1.22- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
10:34:03  [Info] [net.creeperhost.wailt.web.ApiWebServer]: Stopping web server..

**Comment by Brandcraf06** [comment]
Now fixed in 2.9.4

2.9.3 no longer available

**Comment by Wytchcat** [comment]
I saw... Thanks!
