### ISSUE TITLE
Crash with Blockus mentioned due to Rendering Thread error (Minecraft 1.21.1)

### ISSUE THREAD

**Issue by DatrixTheHybridShadowWolf** [Brandcraf06/Blockus#342]
Hi there,
When I went into JEI/EMI I was searching for another item not included in blockus, but ended up crashing due to blockus being mentioned. 

Minecraft: 1.21.1
NeoForge: 21.1.72
FFAPI: 0.104.0+2.0.15
SInytra Connector: 2.0.0-beta.2 & 3 
Connector Extras: 1.12.1
Blockus: 2.9.5

Log File: https://gist.github.com/DatrixTheHybridShadowWolf/f67e46315156bb0ca7d36bf20537c188
Crash Log: https://gist.github.com/DatrixTheHybridShadowWolf/2d5e12ed1011c837fab178d29749f38d

**Comment by Brandcraf06** [comment]
Blockus is a Fabric mod only and not necessarily suited for Neoforge, even with a compatibility mod. I can't do anything at the moment, I'm sorry.

**Comment by DatrixTheHybridShadowWolf** [comment]
Ok no problem. Thanks for the response.
