### ISSUE TITLE
Patterned wool recipes conflict with tarps in Campanion

### ISSUE THREAD

**Issue by sdaugherty** [Brandcraf06/Blockus#36]
The patterned wool recipe in Blockus conflicts with the Tarp recipe in Campanion.

Reported to Campanion here: https://github.com/TerraformersMC/Campanion/issues/30

**Comment by NeusFear** [comment]
Our recipe kind of doesn't make sense anyways, I could probably change it to be a combination of shears and wool in a workbench to give you a tarp instead. We can talk about it on the team.

**Comment by Linguardium** [comment]
in the meantime, i was able to go from wool to patterned wool, then from patterned wool to tarps given that it is lossless

**Comment by NeusFear** [comment]
We have updated our recipe btw, this can be closed.
