### ISSUE TITLE
Iron Gates work as doors

### ISSUE THREAD

**Issue by pjlasl** [Brandcraf06/Blockus#42]
Can you make the iron gates operate as door? It just makes sense :)

**Comment by Brandcraf06** [comment]
> Can you make the iron gates operate as door? It just makes sense :)

Iron Gates already work as iron doors.

**Comment by pjlasl** [comment]
Ah ha! I wasn't aware of this. Thanks!

**Comment by Brandcraf06** [comment]
No problem!
