### ISSUE TITLE
Conflict with logs from Oh The Biomes You'll Go

### ISSUE THREAD

**Issue by sean-work** [Brandcraf06/Blockus#48]
Used Blockus for a long time, great mod, so thank you! One of the players on my server complained that they couldn't strip log/wood blocks from ["Oh The Biomes You'll Go"](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go) mod. So i tested that mod in an isolated instance and there it worked fine. I searched inside the server's mod files for references to "stripped" and got only a handful of results. So i tested disabling each mod on that results list, one at a time, and when i disabled just Blockus, the problem was resolved. 

I know the issue may lie with BYG itself, and not Blockus, but i figured i should mention the incompatibility. Idk if it's because Blockus calls the AxeItem Mixins and BYG doesn't? I tried renaming the files/mod IDs to get minecraft to load the mods in a different order, but no luck either. Anyway, many thanks.

**Comment by CorgiTaco** [comment]
I'm a developer of BYG and would appreciate this issue being resolved soon as several users on my side of the fence are reporting this issue to me. Here's an issue made on my github regarding this: https://github.com/CorgiTaco/BYG/issues/158
