### ISSUE TITLE
Option to disable barrel-related stuff

### ISSUE THREAD

**Issue by crabdancing** [Brandcraf06/Blockus#54]
The custom barrels are pretty and nice to have, but they seem like they're more trouble than they're worth in my modpack, and I suspect I'm not alone on this:

* Barrel-related stuff prevents user from crafting barrels using wood from other mods
    * I ran into this with BYG, but I'm sure it applies in many other places.
* Barrel-related produces inconsistent style in modpacks
   * It seems weird to be able to have a bunch of different types of barrel, and only one type of chest.

Given these concerns, it seems worth considering some way of disabling barrels in Blockus. And in the long run maybe adding a system for creating barrels dynamically from wood types instead of having to explicitly add support for each wood type, and doing the same for chests. :)

**Comment by Brandcraf06** [comment]
Sorry, I currently don't know how to disable blocks (with configs) without creating huge log spam. 
It will happen, if I find how

**Comment by crabdancing** [comment]
Oh, is it that difficult? Seems like it should be possible to add logic to registering the blocks and items... is the log spam from warnings that there are recipes with unknown objects? Seems like the way to fix that would be to add the recipes programmatically using a `JsonObject`. Bear in mind I've never done this before, but that's my suggestion. :P

**Comment by crabdancing** [comment]
There's also an advantage to it in being able to programmatically change recipes later on as needed. For example, you could detect if there's e.g. silver ore added to the game, and iff so add silver bars like the gold bars. :) It'd also be good for bypassing some of the redundancy intrinsic to the data driven approach.

If this is the approach you want to take, I'd probably start by writing a program to automatically convert the .json files into json object declarations for being added to mod initializer. I could easily do this in Python if the project needs it! :D

We'd just need to find some example code of how to make the jsons dynamically... maybe should ask around the Fabric Discord.

**Comment by crabdancing** [comment]
@Brandcraf06 Hey, does [this](https://github.com/natanfudge/fabric-docs/blob/master/newdocs/Modding-Tutorials/Crafting-Recipes/using-dfu-in-crafting-recipes.md) help?

**Comment by saltyseadoggo** [comment]
It may suit your needs to use [KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric) to disable Blockus' barrel recipes, as that sort of tweak for modpacks is what it's made for. I've seen All of Fabric 3 use it, for example. [Fabrication's](https://www.curseforge.com/minecraft/mc-mods/fabrication) Yeet Recipes feature can also remove recipes entirely if you include it in your pack. Your first issue is harder to fix, as Blockus replaces the vanilla barrel recipe with one that only accepts spruce wood, but you can fix that by using KubeJS again to replace the barrel recipe with the vanilla one that uses plank and slab tags to fix it.~

**Comment by Brandcraf06** [comment]
Barrels recipes removed for some reasons
