### ISSUE TITLE
Feature Request: additional basalt blocks

### ISSUE THREAD

**Issue by campbebj** [Brandcraf06/Blockus#67]
buttons, pressure plates, walls, etc. similar to what this mod adds for forge https://www.curseforge.com/minecraft/mc-mods/basalt-blocks

**Comment by saltyseadoggo** [comment]
[BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether) adds a basalt slab, and a set of basalt brick blocks, including a wall, stairs and a slab. It's not everything that the mod you linked provides, and it's part of a larger biome mod, but it may tide you over.~
