### ISSUE TITLE
Leaves are not tagged as leaves?

### ISSUE THREAD

**Issue by K0-RR** [Brandcraf06/Blockus#70]
TinyTweaks removes collision from leaves, for some reason when I enter into a leaves block from blockus it's not transparent.
https://github.com/Hephaestus-Dev/TinyTweaks/issues/48

**Comment by Brandcraf06** [comment]
The leaves are tagged as leaves, the problem is that some parameters of the leaves (and glass) are not considered. It will be corrected for the next update!
