### ISSUE TITLE
Config to disable vanilla item compostability changes

### ISSUE THREAD

**Issue by saltyseadoggo** [Brandcraf06/Blockus#74]
*Blockus* makes the vanilla grass block, mycelium, podzol, dirt, coarse dirt and rotten flesh items compostable. This change to vanilla behaviour is undocumented on the CurseForge page, and is thus "sneaked" into players' games without them knowing what mod is responsible for it. In addition, this change I feel is out of scope for a block focused on adding building blocks, and would be better suited for a vanilla tweaks type of mod.

I would like to request that, at the very least, a configuration option to disable changes to vanilla item compostability be made to let players turn off these changes if they are unwanted, as, right now, the player has to accept them in order to play with Blockus. This configuration option should also turn off the ability to compost this mod's rotten flesh block, so as to line up with vanilla rotten flesh's non-compostability.

**Comment by BrekiTomasson** [comment]
~~Similar to the worldgen issue, let me know and I can PR this in for you.~~

**Edit**: Never mind, just noticed that you removed the ability to compost these things in a recent update. Suggest closing this issue as it is no longer relevant.
