### ISSUE TITLE
Nitpick: Replace minecraft:flammable_planks with c:planks_that_burn

### ISSUE THREAD

**Issue by saltyseadoggo** [Brandcraf06/Blockus#77]
The charred planks recipe uses a new tag to discern what planks are applicable for it, as you know. However, this tag is a bit unorthodox in nature. Firstly, it's in the vanilla Minecraft namespace despite not being a vanilla tag. Putting it into the c namespace is the usual procedure for compatibility tags. Secondly, if you were to follow vanilla Minecraft's naming conventions for tags, flammable_planks would make more sense as planks_that_burn, after vanilla's logs_that_burn.

These are nitpicks, but I anticipate hearing these same issues from other developers when I try to request that they add their planks to the tag so they can be used to make charred planks.

**Comment by Brandcraf06** [comment]
Indeed, I hadn't seen it like that
