### ISSUE TITLE
Blockus should not change Vanilla item models.

### ISSUE THREAD

**Issue by LambdAurora** [Brandcraf06/Blockus#80]
I don't know why this is a thing, flower pot makes sense because of the large flower pots.

But hoppers? I really don't like them being 3D.

Please use [optional built-in resource packs](https://maven.fabricmc.net/docs/fabric-api-0.31.0+1.16/net/fabricmc/fabric/api/resource/ResourceManagerHelper.html#registerBuiltinResourcePack(net.minecraft.util.Identifier,net.fabricmc.loader.api.ModContainer,net.fabricmc.fabric.api.resource.ResourcePackActivationType)) for those kind of things as it can be quite unwanted. It'll allows players to choose if they want to use the feature or not.

**Comment by haykam821** [comment]
Hopper item models were fixed in df0359a4fb17110779f28411b9fbdb80ce2b7c5d
