### ISSUE TITLE
Redstone variants of lanterns?

### ISSUE THREAD

**Issue by muzikbike** [Brandcraf06/Blockus#81]
Currently blockus adds soul o'lanterns for consistency since vanilla has jack o'lanterns and soul torches, yet no soul equivalent of the jack o'lantern. Vanilla, however, also has the redstone torch, with no lantern equivalent in either vanilla or the mod. Perhaps such a thing could be added?

This could be extended to more missing features: there is no redstone lantern (nor redstone lantern block with the mod), so this could be added for balancing, and to take it to the extremes, there could even be red fire, created by setting the top of a redstone block (controllable via a block tag) on fire.

These could possibly also function as redstone components: redstone o'lanterns could still act as not gates, but their output would be facing exclusively up and the other five sides could be used as inputs. Redstone lanterns would also act like redstone torches, but their outputs would always face down, and only accept power from above.

![2021-03-04_20 34 56](https://user-images.githubusercontent.com/52297970/110027517-fb689b80-7d29-11eb-895f-0e1c8e1933a7.png)

**Comment by saltyseadoggo** [comment]
It'd prob make more sense for the redstone jack o' lantern to output power from the side with the carved face on it, like the other sides are all insulated by the pumpkin shell. So it becomes a solid redstone torch that can be powered directly instead of through an adjacent block, and only outputs power through one side.

**Comment by muzikbike** [comment]
Forgot to mention: redstone campfires are another potential result.

**Comment by SpiderKolo** [comment]
Going further with idea: Dyed Light sources.
Torches, Lanterns, Campfires, Fire itself...
While it would be great if the light produced by those sources were also colored, there isn't any support for that in minecraft sadly.
But just the texture itself would be good enough.

Also - Rainbow Lights! Anyone?
