### ISSUE TITLE
Ore types for all stones (Within the dimensions they're found in)

### ISSUE THREAD

**Issue by qwertious** [Brandcraf06/Blockus#86]
In the new 1.17 snapshots, Minecraft has deepslate ore. I was wondering if they would add andesite, diorite, granite, and tuff ores as well but it doesn't seem like they will. Because 1.17 is not released yet, I think it would be cool to have different ore variants for granite, diorite, andesite, bluestone, marble, and limestone. I'd imagine it would take a lot of effort, but then I see all the different colored tiles and combinations of colors in some of the tiles and I think it would be cool!

**Comment by Brandcraf06** [comment]
The idea is very interesting, but not for Blockus
