### ISSUE TITLE
A yellow and green nether forest biome!

### ISSUE THREAD

**Issue by qwertious** [Brandcraf06/Blockus#87]
Red and blue is good, and they are two primary colors that the eye can see, but the neurons in our eyes have two other colors that are basically distinct from the others.

Basically, I want a yellow and green nether forest biome!

**Comment by qwertious** [comment]
This would make the nether a dimension with all the basic colors in it, making it more colorful than it already is.

**Comment by saltyseadoggo** [comment]
[BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) adds the *Sythian Torrids* biome, which is a yellow fungal biome. It may be exactly what you desire, at least for the yellow.~
