### ISSUE TITLE
Asphalt should apply a movement speed attribute modifier rather than granting the speed status effect

### ISSUE THREAD

**Issue by haykam821** [Brandcraf06/Blockus#91]
Granting the speed status effect is unnecessary and conflicts with the actual speed status effect. Like soul speed, the attribute modifier should be affected directly.

**Comment by Brandcraf06** [comment]
Soul speed is handled differently. Asphalt need to apply an attribute modifier to entities without going through an intermediate object (like a piece of armor). This means that it's the block that manages the speed. And to be honest, I have no idea how to do that. But indeed, I know that it would be much better and clean

**Comment by kwpugh** [comment]
Howdy, just happened to see this.   An easy way is to add a  .slipperiness(0.50F)  to the blocks properties.  Will add a nice little pep in the step.

**Comment by SpiderKolo** [comment]
A small suggestion while at Asphalt:
Rainbow Asphalt. That's... really it.

You know... rainbow road and that jazz.

Like I assume more rainbow blocks are coming at some point in future, but I just wanted to mention it while at the topic of Asphalt.

Perhaps having some sort of dyed dusts which you can spread/put on any blocks just like redstone as a way to mark the streets with specific colors and marks?

**Comment by funkychicken493** [comment]
You could apply a velocityMultiplier to asphalt. Something like .velocityMultiplier(1.5F) to the block settings. @Brandcraf06
