### ISSUE TITLE
Add sturdy blackstone

### ISSUE THREAD

**Issue by haykam821** [Brandcraf06/Blockus#92]
There should be a complementary blackstone variant of sturdy stone (which was added in #49). Rather than using stone and cobblestone in its recipe, it should use polished blackstone and blackstone. Other than its darker appearance and different recipe, sturdy blackstone should function exactly like sturdy stone.

**Comment by Brandcraf06** [comment]
Okay 

![image](https://user-images.githubusercontent.com/16505254/113775630-4d398280-9729-11eb-80b8-d08e98fc342f.png)
