### ISSUE TITLE
Skyblock-obtainable bluestone, marble, limestone, white oak

### ISSUE THREAD

**Issue by saltyseadoggo** [Brandcraf06/Blockus#95]
*Blockus,* I've found, is a great mod for modded skyblock worlds, as most of its blocks are crafted using vanilla materials that can generally be obtained and farmed in such an environment. The exceptions to this are the stones marble, limestone and bluestone, and white oak wood, all of which are exclusive to world generation. I would like to see means of obtaining these blocks outside of world generation be added to the mod so that these blocks and their derivative blocks can be played with in skyblock.
Some ideas are:
- Add the white oak sapling to the wandering trader's trades, since the wandering trader sells all vanilla saplings. Following vanilla pricing, it would sell for five emeralds per sapling.
- Add some sort of crafting recipes for the stones based loosely on real world geology, like the vanilla recipes for diorite, andesite and granite in vanilla that use cobblestone, quartz, and diorite, which is made from those two. I'm not entirely sure what these would be; hopefully you know more than I do here. Marble and limestone are similar stones in the real world made from different types of calcium carbonate, and bones are memetic for their calcium content, so perhaps a 2x2 checkerboard of cobblestone and bone meal creates marble, for example?

**Comment by haykam821** [comment]
I have opened #96 to make white oak saplings obtainable from wandering traders.

**Comment by Brandcraf06** [comment]
I hadn't thought about the wandering trader (and thanks haykam821)
For recipes, bluestone has one, marble has one in 1.17 with calcite and limestone but I can replace calcite by bone meal as suggested for 1.16 and for limestone I would find something suitable.
